services:

  postgres:
    image: postgres:17
    container_name: shoposaka-postgres

    environment:
      POSTGRES_DB: shopOsaka
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: shoposaka-app

    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}

      APP_PORT: ${APP_PORT}

    ports:
      - "8080:8080"

    depends_on:
      - postgres

volumes:
  postgres_data:
